spring:
  datasource:
    url: jdbc:mysql://localhost:3307/homolo?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    encoding: utf-8
  redis:
    database: 0
    host: localhost
    port: 6380
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
    timeout: 5000
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: 123456
    in-memory: false
    pool:
      enabled: true
      max-connections: 10
server:
  port: 8086
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jetty.homolo.security.entity
  config-location: classpath:mybatis-config.xml